package GUIs;

import Shows.ShowList;
import java.awt.FlowLayout;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author DOUAE
 */
public class NetflixAppGUI extends javax.swing.JFrame {

    public static ShowList shows;
    private JTabbedPane tabs;

    /**
     * Creates new form NewJFrame
     */
    public NetflixAppGUI() {
        setTitle("Netflix Application: ");
        setLayout(new FlowLayout());

        tabs = new JTabbedPane();
        shows = new ShowList();

        try {
            shows.load();
        } catch (ClassNotFoundException ex) {
            System.err.println("Class not found.");
            JOptionPane.showMessageDialog(NetflixAppGUI.this, "" + "An Error Occurred While Loading shows.", "Load Changes", JOptionPane.ERROR_MESSAGE);
            System.err.println(ex.getMessage());
        } catch (IOException ex) {
            System.err.println("Cannot deserialize shows.");
            JOptionPane.showMessageDialog(NetflixAppGUI.this, "" + "An Error Occurred While Loading shows.", "Load Changes", JOptionPane.ERROR_MESSAGE);
            System.err.println(ex.getMessage());
        }

        tabs.addTab("Search", null, new NetflixSearchPanel());
        tabs.addTab("Add/Edit/Delete", null, new CRUDNetflixPanel());
        add(tabs);
        this.pack();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        SavejMenuItem = new javax.swing.JMenuItem();
        ExitjMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AboutjMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOUAE\\Pictures\\Homesmall.png")); // NOI18N
        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        SavejMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SavejMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOUAE\\Pictures\\Savesmall.png")); // NOI18N
        SavejMenuItem.setText("Save");
        SavejMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavejMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(SavejMenuItem);

        ExitjMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ExitjMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOUAE\\Pictures\\Exitsmall.png")); // NOI18N
        ExitjMenuItem.setText("Exit");
        ExitjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitjMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(ExitjMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOUAE\\Pictures\\Helpsmall.png")); // NOI18N
        jMenu2.setText("Help");

        AboutjMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AboutjMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\DOUAE\\Pictures\\Aboutsmall.png")); // NOI18N
        AboutjMenuItem.setText("About");
        AboutjMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutjMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(AboutjMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 781, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void SavejMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavejMenuItemActionPerformed
        // TODO add your handling code here:

        try {
            shows.save();
            JOptionPane.showMessageDialog(NetflixAppGUI.this, "" + "Changes Saved Successfully.", "Save Changes", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.err.println("Cannot serialize shows.");
            JOptionPane.showMessageDialog(NetflixAppGUI.this, "" + "An Error Occurred While Saving Changes.", "Save Changes", JOptionPane.ERROR_MESSAGE);
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_SavejMenuItemActionPerformed

    private void ExitjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitjMenuItemActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(NetflixAppGUI.this, "Do you want to exit Netflix?", "Netflix: Exit", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitjMenuItemActionPerformed

    private void AboutjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutjMenuItemActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(NetflixAppGUI.this, "Netflix.com is a subscription-based streaming service that allows members to watch TV shows and movies\n" +
"without commercials on an internet-connected device. Java project by Douae Essalhi", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AboutjMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NetflixAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NetflixAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NetflixAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NetflixAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NetflixAppGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutjMenuItem;
    private javax.swing.JMenuItem ExitjMenuItem;
    private javax.swing.JMenuItem SavejMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
